### ISSUE TITLE
Joining hyperion-project

### ISSUE THREAD

**Issue by EladKeyshawn** [hyperion-project/hyperion.android#1]
Hi I'd like to learn and contribute , i'd love to join your organization!

Thanks!

**Comment by brindosch** [comment]
Greetings @EladKeyshawn,
thank you for your interest in hyperion. For sure you had a idea in mind with a "personal" target or just out of the wild "what can i do?".

**Comment by EladKeyshawn** [comment]
@brindosch To be honest this project looks pretty abundant therefore it was actually a general question of how can I contribute 😄

**Comment by brindosch** [comment]
There is always something to do indeed. But it's up to your motivation what you want to learn. 
- Hyperion itself is written in C++, the effects are written in python.
- For improvements of the web configuration you need html, css and javascript
- Another thing is CMake, we currently miss for example cross compilation for RPi and 64bit arm for the hyperion.ng repo which needs to be added in order to test pull requests automated
- CPack to create install packages for every platform and test them
- Create a windows version of hyperion, it's doable but requires time and testing.

Do you have any knowledge which may help you to getting started into a certain area (keep motivation with faster success)? Even with zero knowledge all you need is time (this is highest factor where a lot of people lack of), stamina and patience while improving your knowledge about something.

I am here for question, also @redPanther can help and answer question if required. Just leave your thoughts
